version: '3'
services:
  dev:
    build:
      context:    .
      dockerfile: Dockerfile
    image: ojos/vscode-remote-for-node/dev
    container_name: dev
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /workspaces/.aws/credentials
      AWS_CONFIG_FILE:             /workspaces/.aws/config
      APP_ENV:                     local-dev
      MYSQL_HOST:                  db
      MYSQL_USER:                  sample
      MYSQL_PASSWORD:              sample
      MYSQL_DATABASE:              sample
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/node/.ssh
      - ~/.gitconfig:/home/node/.gitconfig
      - ../:/workspaces
      - ../tmp/log/app:/var/log/app
    ports:
      - 3000:3000
    command: sleep infinity 